"""Remove Admin

Revision ID: 34b6d580dd68
Revises: 34f79ac2bda5
Create Date: 2025-06-25 13:20:54.558550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34b6d580dd68'
down_revision: Union[str, Sequence[str], None] = '34f79ac2bda5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
