"""Added_Order_Items_Table

Revision ID: 4b52543f5015
Revises: 8b692f33b7ff
Create Date: 2025-07-04 15:45:30.846450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b52543f5015'
down_revision: Union[str, Sequence[str], None] = '8b692f33b7ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('flavor', sa.String(), nullable=False))
    op.add_column('order_items', sa.Column('size', sa.String(), nullable=False))
    op.add_column('order_items', sa.Column('unity_price', sa.Float(), nullable=False))
    op.drop_column('order_items', 'product_id')
    op.drop_column('order_items', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('price', sa.FLOAT(), nullable=False))
    op.add_column('order_items', sa.Column('product_id', sa.INTEGER(), nullable=False))
    op.drop_column('order_items', 'unity_price')
    op.drop_column('order_items', 'size')
    op.drop_column('order_items', 'flavor')
    # ### end Alembic commands ###
