"""Added Table Order

Revision ID: 8b692f33b7ff
Revises: 52e3ecd3bce2
Create Date: 2025-06-26 13:16:58.828686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b692f33b7ff'
down_revision: Union[str, Sequence[str], None] = '52e3ecd3bce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'product_id')
    op.drop_column('orders', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('quantity', sa.INTEGER(), nullable=False))
    op.add_column('orders', sa.Column('product_id', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
